# Generated by Django 5.2.7 on 2025-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
