# Generated by Django 5.2.7 on 2025-11-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlashAI', '0003_studystreak_studysession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studystreak',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
        migrations.DeleteModel(
            name='StudyStreak',
        ),
    ]
